### ISSUE TITLE
Allow users to select difficulty of problem

### ISSUE THREAD

**Issue by The-CodingSloth** [The-CodingSloth/haha-funny-leetcode-extension#4]
Create the functionality of letting users to pick out difficulty of leetcode problems, so in the extension they have the option to only select easy, medium, hard problems, and an any difficulty option.
1. Might have to modify the web scraper to scrape the difficulty of problems as well.
2. Modify JSON file format to now include difficulty.
3.  Modify the popup to have something to let users select difficulty.

**Comment by Tayomide** [comment]
I could make a pull request with this changes

I will try doing that today

**Comment by The-CodingSloth** [comment]
Awesome sounds good!

**Comment by Tayomide** [comment]
I just made a pull request that should fix this

I will check out the Figma file now! I couldn't earlier because I was being redirected to solve a problem on leetcode

It takes a while for the problems to be updated when the difficulty changes. Maybe we could add a loading bar to show it is working on it or store the problem list somewhere after the initial request
