### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by The-CodingSloth** [The-CodingSloth/haha-funny-leetcode-extension#9]
Currently using JavaScript throughout this whole extension and that's some Junior Developer behavior. TypeScript support would help a lot and make this look more professional because we're all 10x developers here.

Here's a link for chrome type package to get started:
[chrome type package](https://www.npmjs.com/package/chrome-types)

**Comment by slav-getov** [comment]
Hey, idk if this was intentional but the link you provided does not actually lead to where you want - it leads to: 'https://github.com/The-CodingSloth/haha-funny-leetcode-extension/issues/url'. 

Anyways, for anyone else interested @The-CodingSloth wanted to link [here](https://www.npmjs.com/package/chrome-types). Thank you for making that video on the extension!

**Comment by The-CodingSloth** [comment]
haha thanks so much I'm dumb sometimes

**Comment by green1490** [comment]
I rewrote the codebase into typescript besides the test scripts. The only thing that is left is to handle undefined cases to reduce the spagetti.
https://github.com/green1490/haha-funny-leetcode-extension/tree/feature/typescript-support
